AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: StriveSync Backend API - Unified Stack (Auth, Users, Data)

Parameters:
  CognitoUserPoolName:
    Type: String
    Default: StriveSyncUserPool
    Description: Name of the Cognito User Pool.
  CognitoUserPoolClientName:
    Type: String
    Default: StriveSyncWebAppClient
    Description: Name of the Cognito User Pool Client for web applications (client-side auth).
  CognitoUserPoolAdminClientName:
    Type: String
    Default: StriveSyncAdminAppClient
    Description: Name of the Cognito User Pool Client for admin/backend services.
  UsersTableName:
    Type: String
    Default: StriveSyncUsers
    Description: Name of the DynamoDB table for user profiles.

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        COGNITO_USER_POOL_ID: !Ref StriveSyncUserPool
        COGNITO_CLIENT_ID: !Ref StriveSyncUserPoolClient
        COGNITO_ADMIN_CLIENT_ID: !Ref StriveSyncUserPoolAdminClient
        USERS_TABLE_NAME: !Ref UsersTable

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref UsersTableName
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  StriveSyncUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref CognitoUserPoolName
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: preferred_username
          AttributeDataType: String
          Mutable: true
          Required: false
          StringAttributeConstraints:
            MinLength: '3'
            MaxLength: '50'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      MfaConfiguration: "OFF"

  StriveSyncUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Ref CognitoUserPoolClientName
      UserPoolId: !Ref StriveSyncUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false

  StriveSyncUserPoolAdminClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Ref CognitoUserPoolAdminClientName
      UserPoolId: !Ref StriveSyncUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

  # --- START API GATEWAY DEFINITION WITH ALL PATHS (DefinitionBody) ---
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: StriveSyncApi
      StageName: Prod
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: StriveSync API
          version: "1.0"
        paths:
          # --- GET /users/me PATH ---
          /users/me:
            get:
              responses:
                "200":
                  description: Get user profile
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUserProfileFunction.Arn}/invocations
                httpMethod: POST # Correct for Lambda proxy integration
                type: aws_proxy
              security:
                - CognitoAuth: [] # Applies the Cognito Authorizer
          # --- END GET /users/me PATH ---

          # --- POST /auth/signup PATH ---
          /auth/signup:
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema: # Placeholder for SignupRequest schema
                      type: object
                      properties:
                        email: { type: string }
                        password: { type: string }
                        username: { type: string }
                      required: [email, password, username]
              responses:
                "200":
                  description: User signup response
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SignupFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          # --- END POST /auth/signup PATH ---

          # --- POST /auth/confirm-signup PATH ---
          /auth/confirm-signup:
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema: # Placeholder for ConfirmSignupRequest schema
                      type: object
                      properties:
                        email: { type: string }
                        verificationCode: { type: string }
                      required: [email, verificationCode]
              responses:
                "200":
                  description: Confirm signup response
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConfirmSignupFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          # --- END POST /auth/confirm-signup PATH ---

          # --- POST /auth/login PATH ---
          /auth/login:
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema: # Placeholder for LoginRequest schema
                      type: object
                      properties:
                        email: { type: string }
                        password: { type: string }
                      required: [email, password]
              responses:
                "200":
                  description: Login response
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LoginFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          # --- END POST /auth/login PATH ---

        components:
          securitySchemes:
            # --- Cognito Authorizer Definition ---
            CognitoAuth:
              type: apiKey
              name: Authorization
              in: header
              x-amazon-apigateway-authtype: cognito_user_pools
              x-amazon-apigateway-authorizer:
                type: cognito_user_pools
                providerARNs:
                  - !GetAtt StriveSyncUserPool.Arn
            # --- END Cognito Authorizer Definition ---
  # --- END API GATEWAY DEFINITION WITH ALL PATHS ---

  # --- START FUNCTION DEFINITIONS (NO API Events here when using DefinitionBody) ---
  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/
      Handler: handler.signupHandler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - cognito-idp:SignUp
              - cognito-idp:AdminRespondToAuthChallenge
            Resource: !GetAtt StriveSyncUserPool.Arn
        - DynamoDBWritePolicy:
            TableName: !Ref UsersTable
      # Events removed as defined in ServerlessRestApi.DefinitionBody
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        External: ["@aws-sdk/*"]
        Sourcemap: true

  # --- ADDED: API Gateway permission to invoke SignupFunction ---
  SignupFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SignupFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessRestApi}/*/*" # Allows any method/path on this API

  ConfirmSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/
      Handler: handler.confirmSignupHandler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - cognito-idp:ConfirmSignUp
              - cognito-idp:ResendConfirmationCode
            Resource: !GetAtt StriveSyncUserPool.Arn
      # Events removed
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        External: ["@aws-sdk/*"]
        Sourcemap: true

  # --- ADDED: API Gateway permission to invoke ConfirmSignupFunction ---
  ConfirmSignupFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ConfirmSignupFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessRestApi}/*/*"

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth/
      Handler: handler.loginHandler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - cognito-idp:AdminInitiateAuth
              - cognito-idp:AdminGetUser
            Resource: !GetAtt StriveSyncUserPool.Arn
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      # Events removed
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        External: ["@aws-sdk/*"]
        Sourcemap: true

  # --- ADDED: API Gateway permission to invoke LoginFunction ---
  LoginFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LoginFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessRestApi}/*/*"

  GetUserProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/users/
      Handler: handler.getUserProfileHandler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      # Events removed
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        External: ["@aws-sdk/*"]
        Sourcemap: true

  # --- ADDED: API Gateway permission to invoke GetUserProfileFunction ---
  GetUserProfileFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt GetUserProfileFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessRestApi}/*/*"

  # --- END FUNCTION DEFINITIONS ---

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL for all functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  StriveSyncUserPoolId:
    Description: "ID of the StriveSync Cognito User Pool"
    Value: !Ref StriveSyncUserPool

  StriveSyncUserPoolClient:
    Description: "ID of the Cognito User Pool Client (Web/Mobile App)"
    Value: !Ref StriveSyncUserPoolClient

  StriveSyncUserPoolAdminClient:
    Description: "ID of the Cognito User Pool Admin Client (Backend)"
    Value: !Ref StriveSyncUserPoolAdminClient

  UsersTableName:
    Description: "Name of the DynamoDB Users table"
    Value: !Ref UsersTable